import java.io.IOException;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Properties;
import java.util.Calendar;
import java.util.HashMap;
// import javax.mail.BodyPart;
// import javax.mail.Message;
// import javax.mail.MessagingException;
// import javax.mail.Multipart;
// import javax.mail.PasswordAuthentication;
// import javax.mail.Session;
// import javax.mail.Transport;
// import javax.mail.internet.InternetAddress;
// import javax.mail.internet.MimeBodyPart;
// import javax.mail.internet.MimeMessage;
// import javax.mail.internet.MimeMultipart;

public class CreateChiUploader
{
    // socket for connection to SISServer
    static Socket universal;
    private static int port = 53217;
    // message writer
    static MsgEncoder encoder;
    // message reader
    static MsgDecoder decoder;
    // shared by all kinds of records that can be generated by this component
    private static KeyValueList record = new KeyValueList();
    // shared by all kinds of alerts that can be generated by this component
    private static KeyValueList alert = new KeyValueList();

    // scope of this component
    private static final String SCOPE = "SIS.Chi";
    // name of this component
    private static final String NAME = "ChiUploader";
    // messages types that can be handled by this component
    private static final List<String> TYPES = new ArrayList<String>(
        Arrays.asList(new String[] { "Alert", "Emergency", "Confirm", "Setting","Reading"}));

    private static UploaderReading reading = new UploaderReading();

    private static Group group = new Group();

    // variables for sending emails
    // static final String SMTP_HOST_NAME = "smtp.ksiresearch.org.ipage.com";
    // static final String SMTP_PORT = "587";
    // static final String emailMsgTxt = "Test Message Contents";
    // static final String emailSubjectTxt = "Personal Healthcare Data From SIS System."; // title
    // static final String emailFromAddress = "chronobot@ksiresearch.org";
    // static final String SSL_FACTORY = "javax.net.ssl.SSLSocketFactory";

    /*
     * Main program
     */
    public static void main(String[] args)
    {
        while (true)
        {
            try
            {
                // try to establish a connection to SISServer
                universal = connect();

                // bind the message reader to inputstream of the socket
                decoder = new MsgDecoder(universal.getInputStream());
                // bind the message writer to outputstream of the socket
                encoder = new MsgEncoder(universal.getOutputStream());

                /*
                 * construct a Connect message to establish the connection
                 */
                KeyValueList conn = new KeyValueList();
                conn.putPair("Scope", SCOPE);
                conn.putPair("MessageType", "Connect");
                conn.putPair("Role", "Advertiser");
                conn.putPair("Name", NAME);
                encoder.sendMsg(conn);

                initRecord();

                // KeyValueList for inward messages, see KeyValueList for
                // details
                KeyValueList kvList;

                // update();

                while (true)
                {
                    // attempt to read and decode a message, see MsgDecoder for
                    // details
                    kvList = decoder.getMsg();

                    // process that message
                    ProcessMsg(kvList);
                }

            }
            catch (Exception e)
            {
                // if anything goes wrong, try to re-establish the connection
                e.printStackTrace();
                try
                {
                    // wait for 1 second to retry
                    Thread.sleep(1000);
                }
                catch (InterruptedException e2)
                {
                }
                System.out.println("Try to reconnect");
                try
                {
                    universal = connect();
                }
                catch (IOException e1)
                {
                }
            }
        }
    }

    /*
     * used for connect(reconnect) to SISServer
     */
    static Socket connect() throws IOException
    {
        Socket socket = new Socket("127.0.0.1", port);
        return socket;
    }

    private static void initRecord() {
        record.putPair("Scope", SCOPE);
        record.putPair("MessageType", "Reading");
        record.putPair("Sender", NAME);

        // Receiver may be different for each message, so it doesn't make sense
        // to set here
        // record.putPair("Receiver", "");

        alert.putPair("Scope", SCOPE);
        alert.putPair("MessageType", "Alert");
        alert.putPair("Sender", NAME);
        alert.putPair("Purpose", "ChiAlert");

        // Receiver may be different for each message, so it doesn't make sense
        // to set here
        // alert.putPair("Receiver", "");
    }



    /*
     * Method for sending email which contains the information which GUI shows
     * on screen.
     */
    // static void sendSSLMessage(String from, String recipients[],
    //                            String subject, String message) throws MessagingException
    // {
    //     boolean debug = false;
    //     Properties props = new Properties();
    //     props.put("mail.smtp.host", SMTP_HOST_NAME);
    //     props.put("mail.smtp.auth", "true");
    //     props.put("mail.debug", "true");
    //     props.put("mail.smtp.port", SMTP_PORT);
    //     props.put("mail.smtp.socketFactory.port", SMTP_PORT);
    //     props.put("mail.smtp.socketFactory.class", SSL_FACTORY);
    //     props.put("mail.smtp.socketFactory.fallback", "true");

    //     Session session = Session.getDefaultInstance(props,
    //                       new javax.mail.Authenticator()
    //     {
    //         protected PasswordAuthentication getPasswordAuthentication()
    //         {
    //             return new PasswordAuthentication(
    //                        "chronobot@ksiresearch.org", "Health14");
    //         }
    //     });
    //     session.setDebug(debug);

    //     Message msg = new MimeMessage(session);
    //     InternetAddress addressFrom = new InternetAddress(from);
    //     msg.setFrom(addressFrom);

    //     InternetAddress[] addressTo = new InternetAddress[recipients.length];
    //     for (int i = 0; i < recipients.length; i++)
    //     {
    //         addressTo[i] = new InternetAddress(recipients[i]);
    //     }
    //     msg.setRecipients(Message.RecipientType.TO, addressTo);
    //     msg.setSubject(subject);
    //     {
    //         Multipart multipart = new MimeMultipart("related");
    //         {
    //             Multipart newMultipart = new MimeMultipart("alternative");
    //             BodyPart nestedPart = new MimeBodyPart();
    //             nestedPart.setContent(newMultipart);
    //             multipart.addBodyPart(nestedPart);
    //             {
    //                 BodyPart part = new MimeBodyPart();
    //                 part.setText("SIS DATA:");
    //                 newMultipart.addBodyPart(part);

    //                 part = new MimeBodyPart();
    //                 // the first string is email context

    //                 part.setContent(
    //                     "Here is the current status of the patient "
    //                     + "(This is an automatic massage send from SIS system): "
    //                     + "<br>LastName: "
    //                     + reading.lastName
    //                     + "<br>FirstName: "
    //                     + reading.firstName
    //                     + "<br>Votes: "
    //                     + reading.votes
    //                     + "<br>Date of Votes: "
    //                     + reading.dateVotes,
    //                     // + "<br>SPO2: "
    //   //                   + reading.spo2
    //   //                   + "<br>Systolic: "
    //   //                   + reading.systolic
    //   //                   + "<br>Diastolic: "
    //   //                   + reading.diastolic
    //   //                   + "<br>Pulse: "
    //   //                   + reading.pulse
    //   //                   + "<br>Date of Blood Pressure: "
    //   //                   + reading.dateBP
                //      // + "<br>SPO2: "
    //   //                   + reading.spo2
    //   //                   + "<br>Date of SPO2: "
    //   //                   + reading.dateSPO2
    //   //                   + "<br>EKG: "
    //   //                   + reading.ekg
    //   //                   + "<br>Date of EKG: "
    //   //                   + reading.dateEKG
    //                     + "<br>Temperature: "
    //                     + reading.temp
    //                     + "<br>Date of Temperature: "
    //                     + reading.dateTemp
    //                     + "<br>Kinect Status: "
    //                     // + reading.kinectStatus
    //                     // + "<br>Date of Kinect: "
    //                     // + reading.dateKinect, 
    //                     "text/html");
    //                 newMultipart.addBodyPart(part);
    //             }
    //         }
    //         /*
    //          * BodyPart part = new MimeBodyPart();
    //          * part.setText(
    //          * "Here is the SPO2 and Blood Pressure data(This is an automatic massage send from SIS system): LastName: "
    //          * + lname
    //          * + " FirstName: "
    //          * + fname
    //          * + "\nSPO2: "
    //          * + spo2
    //          * + " "
    //          * + "\nSystolic: "
    //          * + systolic + "\nDiastolic: " + diastolic + "\nPulse: " + pulse);
    //          * multipart.addBodyPart(part);
    //          */
    //         msg.setContent(multipart);

    //     }
    //     Transport.send(msg);
    //     System.out.println("Successfully Sent mail to All Users, lol.\n");
    // }

    // /*
    //  * Method for sending email for Alert Message
    //  */
    // static void sendAlertSSLMessage(String from, String recipients[],
    //                                 String subject, String message) throws MessagingException
    // {
    //     boolean debug = false;
    //     Properties props = new Properties();
    //     props.put("mail.smtp.host", SMTP_HOST_NAME);
    //     props.put("mail.smtp.auth", "true");
    //     props.put("mail.debug", "true");
    //     props.put("mail.smtp.port", SMTP_PORT);
    //     props.put("mail.smtp.socketFactory.port", SMTP_PORT);
    //     props.put("mail.smtp.socketFactory.class", SSL_FACTORY);
    //     props.put("mail.smtp.socketFactory.fallback", "true");

    //     Session session = Session.getDefaultInstance(props,
    //                       new javax.mail.Authenticator()
    //     {
    //         protected PasswordAuthentication getPasswordAuthentication()
    //         {
    //             return new PasswordAuthentication(
    //                        "chronobot@ksiresearch.org", "Health14");
    //         }
    //     });
    //     session.setDebug(debug);

    //     Message msg = new MimeMessage(session);
    //     InternetAddress addressFrom = new InternetAddress(from);
    //     msg.setFrom(addressFrom);

    //     InternetAddress[] addressTo = new InternetAddress[recipients.length];
    //     for (int i = 0; i < recipients.length; i++)
    //     {
    //         addressTo[i] = new InternetAddress(recipients[i]);
    //     }
    //     msg.setRecipients(Message.RecipientType.TO, addressTo);
    //     msg.setSubject(subject);
    //     {
    //         Multipart multipart = new MimeMultipart("related");
    //         {
    //             Multipart newMultipart = new MimeMultipart("alternative");
    //             BodyPart nestedPart = new MimeBodyPart();
    //             nestedPart.setContent(newMultipart);
    //             multipart.addBodyPart(nestedPart);
    //             {
    //                 BodyPart part = new MimeBodyPart();
    //                 part.setText("SIS Alert!");
    //                 newMultipart.addBodyPart(part);

    //             }
    //         }
    //         BodyPart part = new MimeBodyPart();
    //         part.setText(message);
    //         multipart.addBodyPart(part);
    //         msg.setContent(multipart);
    //     }
    //     Transport.send(msg);
    //     System.out.println("Successfully Sent mail to All Users. :)\n");
    // }

    // ============= end of sending email ====================

    private static void ProcessMsg(KeyValueList kvList) throws Exception
    {

        String scope = kvList.getValue("Scope");
        if (!SCOPE.startsWith(scope))
        {
            return;
        }

        String messageType = kvList.getValue("MessageType");
        if (!TYPES.contains(messageType))
        {
            return;
        }

        String sender = kvList.getValue("Sender");

        String receiver = kvList.getValue("Receiver");

        String purpose = kvList.getValue("Purpose");

        switch (messageType)
        {

        case "Reading":
            System.out.println("\n*** Reading from "+sender+" ***");
            reading.up = sender;
            switch (sender)
            {
            case "SocialNetwork":
                String ssUid = kvList.getValue("uid");
                String ssTongue = kvList.getValue("tongue");
                String ssFatigue = kvList.getValue("fatigue");
                String ssWeakBreadth = kvList.getValue("weakBreadth");
                String ssPulse = kvList.getValue("pulse");
                String ssSweaty = kvList.getValue("sweaty");
                String ssDate = kvList.getValue("datetime");
                String ssOriginator = kvList.getValue("originator");
                String ssTotal = kvList.getValue("chiTotal");

                if (ssUid != null && !ssUid.equals("")) {
                    // TODO for testing, I don't need to change the uid here.
                    reading.uid = ssUid;
                }
                if (ssTongue != null && !ssTongue.equals("")) {
                    reading.tongue = Integer.parseInt(ssTongue);
                }
                if (ssFatigue != null && !ssFatigue.equals("")) {
                    reading.fatigue = Integer.parseInt(ssFatigue);
                }
                if (ssWeakBreadth != null && !ssWeakBreadth.equals("")) {
                    reading.weakBreadth = Integer.parseInt(ssWeakBreadth);
                }
                if (ssPulse != null && !ssPulse.equals("")) {
                    reading.pulse = Integer.parseInt(ssPulse);
                }
                if (ssSweaty != null && !ssSweaty.equals("")) {
                    reading.sweaty = Integer.parseInt(ssSweaty);
                }
                if (ssTotal != null && !ssTotal.equals("")) {
                    reading.chiTotal = ssTotal;
                }
                if (ssDate != null && !ssDate.equals(""))
                {
                    reading.dateChiSensor = Long.parseLong(ssDate);
                }
                if (ssOriginator != null && !ssOriginator.equals(""))
                {
                    reading.originator = ssOriginator;
                }
                System.out.println(ssUid);
                System.out.println(ssTongue);
                System.out.println(ssFatigue);
                System.out.println(ssWeakBreadth);
                System.out.println(ssPulse);
                System.out.println(ssSweaty);
                System.out.println(ssDate.toString());
                System.out.println(ssDate.length());
                System.out.println(ssOriginator);
                break;
            case "ChiMonitor":
                reading.purpose = purpose;

                if(purpose.equals("query")){
                    // If the message is correct, I can handle the message here.
                    String table = kvList.getValue("Table");
                    String sql = kvList.getValue("Query");
                    Data data = new Data(table, sql);
                    System.out.println("Receive message from ChiMonitor");
                    try {
                        
                        alert.putPair("Result", data.toString(data));
                        //send reading message to monitor
                        alert.putPair("Receiver", "ChiMonitor");
                        encoder.sendMsg(alert);
                        alert.removePair("Receiver");
                        
                        
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                } else if (purpose.equals("update")||purpose.equals("analysis")) {

                    System.out.println("++++++++++++++++++");
                    System.out.println(purpose);

                    System.out.println("++++++++++++++++++");
                    String sUid = kvList.getValue("uid");
                    String sTongue = kvList.getValue("tongue");
                    String sFatigue = kvList.getValue("fatigue");
                    String sWeakBreadth = kvList.getValue("weakBreadth");
                    String sPulse = kvList.getValue("pulse");
                    String sSweaty = kvList.getValue("sweaty");
                    String sDate = kvList.getValue("datetime");
                    String sTotal = kvList.getValue("chiTotal");

                    //String ssource = kvList.getValue("WebGUI");
                    // Colin
                    String sOriginator = kvList.getValue("originator");
                    // Colin

                    if (sUid != null && !sUid.equals("")) {
                        // TODO for testing, I don't need to change the uid here.
                        reading.uid = sUid;
                    }
                    if (sTongue != null && !sTongue.equals("")) {
                        reading.tongue = Integer.parseInt(sTongue);
                    }
                    if (sFatigue != null && !sFatigue.equals("")) {
                        reading.fatigue = Integer.parseInt(sFatigue);
                    }
                    if (sWeakBreadth != null && !sWeakBreadth.equals("")) {
                        reading.weakBreadth = Integer.parseInt(sWeakBreadth);
                    }
                    if (sPulse != null && !sPulse.equals("")) {
                        reading.pulse = Integer.parseInt(sPulse);
                    }
                    if (sSweaty != null && !sSweaty.equals("")) {
                        reading.sweaty = Integer.parseInt(sSweaty);
                    }
                    if (sTotal != null && !sTotal.equals("")) {
                        reading.chiTotal = sTotal;
                    }
                    if (sDate != null && !sDate.equals(""))
                    {
                        reading.dateChiSensor = Long.parseLong(sDate);
                    }
                    // Colin
                    if (sOriginator != null && !sOriginator.equals("")){
                        reading.originator = sOriginator;
                    }
                    // Colin


                    // if(ssource != null && !ssource.equals("")){
                    //     reading.ssource = ssource;
                    // }

                    System.out.println(sUid);
                    System.out.println(sTongue);
                    System.out.println(sFatigue);
                    System.out.println(sWeakBreadth);
                    System.out.println(sPulse);
                    System.out.println(sSweaty);
                    System.out.println(sDate);
                    // Colin
                    System.out.println(sOriginator);
                    // Colin

                }
                break;
            case "ChiWebGUI":
                // update database for similar result
                String sUid = kvList.getValue("uid");
                String sTongue = kvList.getValue("tongue");
                String sFatigue = kvList.getValue("fatigue");
                String sWeakBreadth = kvList.getValue("weakBreadth");
                String sPulse = kvList.getValue("pulse");
                String sSweaty = kvList.getValue("sweaty");
                String sDate = kvList.getValue("datetime");
                // Colin
                String sOriginator = kvList.getValue("originator");
                // Colin
                //String sTotal = kvList.getValue("chiTotal");

                if (sUid != null && !sUid.equals("")) {
                    // TODO for testing, I don't need to change the uid here.
                    reading.uid = sUid;
                }
                if (sTongue != null && !sTongue.equals("")) {
                    reading.tongue = Integer.parseInt(sTongue);
                }
                if (sFatigue != null && !sFatigue.equals("")) {
                    reading.fatigue = Integer.parseInt(sFatigue);
                }
                if (sWeakBreadth != null && !sWeakBreadth.equals("")) {
                    reading.weakBreadth = Integer.parseInt(sWeakBreadth);
                }
                if (sPulse != null && !sPulse.equals("")) {
                    reading.pulse = Integer.parseInt(sPulse);
                }
                if (sSweaty != null && !sSweaty.equals("")) {
                    reading.sweaty = Integer.parseInt(sSweaty);
                }
                // Colin
                if (sOriginator != null && !sOriginator.equals(""))
                {
                    reading.originator = sOriginator;
                }
                // Colin
                // if (sTotal != null && !sTotal.equals("")) {
                //     reading.chiTotal = sTotal;
                // }
                if (sDate != null && !sDate.equals(""))
                {
                    reading.GUIDate = Long.parseLong(sDate);
                }

                Data data = new Data("records",
                        "Select * From records where DATEDIFF(NOW(),datetime)<20 and source='Analysis' order by rid desc");
                ArrayList<HashMap<String, String>> records = new ArrayList<HashMap<String, String>>();
                HashMap<String, String> record = new HashMap<String, String>();
                String oldDate = "";
                String date = "";
                for (int i = 0; i < data.size(); i++) {
                    // System.out.println(data.getRecord(i, "uid"));
                    // System.out.println(data.getRecord(i, 0));
                    System.out.println(data.getRecord(i));
                    date = data.getRecord(i, "datetime");
                    if (oldDate.equals("") || !oldDate.equals(date)) {
                        if (record.size() == 10) {
                            records.add(record);
                        }
                        oldDate = date;
                        record = new HashMap<String, String>();
                        record.put("uid", data.getRecord(i, "uid"));
                        record.put("datetime", data.getRecord(i, "datetime"));
                        record.put("source", data.getRecord(i, "source"));
                        record.put("originator", data.getRecord(i, "originator"));
                    }

                    if (oldDate.equals(date)) {
                        record.put(data.getRecord(i, "type"), data.getRecord(i, "value"));
                    }
                }

                int[] minInd = new int[3];
                int[] minVal = new int[3];
                for(int i = 0; i < minInd.length; i++) {
                    minInd[i] = 0;
                    minVal[i] = -1;
                }
                for (int i = 0; i < records.size(); i++) {
                    record = records.get(i);
                    int errSweaty = reading.sweaty - Integer.parseInt(record.get("sweaty"));
                    int errPulse = reading.pulse - Integer.parseInt(record.get("pulse"));
                    int errWeakBreadth = reading.weakBreadth - Integer.parseInt(record.get("weakBreadth"));
                    int errFatigue = reading.fatigue - Integer.parseInt(record.get("fatigue"));
                    int errTongue = reading.tongue - Integer.parseInt(record.get("tongue"));
                    int result = errSweaty * errSweaty + errPulse * errPulse + errWeakBreadth * errWeakBreadth
                            + errFatigue * errFatigue + errTongue * errTongue;
                    for(int j = 0; j < minInd.length; j++) {
                        if (minVal[j] < 0 || minVal[j] > result) {
                            minInd[j] = i;
                            minVal[j] = result;
                            break;
                        }
                    }
                }

                reading.records = new ArrayList<HashMap<String, String>>();
                for (int i = 0; i < minInd.length; i++) {
                    if (minVal[i] != -1) {
                        reading.records.add(records.get(minInd[i]));
                    }
                    
                }
                //record = records.get(minInd);
                // Colin
                reading.record = record;
                // Colin
                System.out.println(reading.record);
                reading.sim = reading.record.get("uid");
                 // + ", " + record.get("datetime") + ", " + record.get("source") + ", "
                 //        + record.get("originator") + ", " + record.get("tongue") + ", " + record.get("fatigue") + ", "
                 //        + record.get("weakBreadth") + ", " + record.get("pulse") + ", " + record.get("sweaty") + ", "
                 //        + record.get("chiTotal");
                System.out.println(reading.sim);
                break;

            }
            System.out.println("Start Advertising...\n");
            update();
            // sendSSLMessage(emailFromAddress, reading.recipients, emailSubjectTxt,
            //            emailMsgTxt);
            System.out.println("Data Advertised\n");
            break;

        // case "Emergency":
        //     String sup = kvList.getValue("MainComponent");
        //     String auxs = kvList.getValue("HelperComponents");
        //     String note = kvList.getValue("Note");

        //     System.out.println("\n*** Emergency Alert from " + sup + " backed by " + auxs+" ***");

        //     System.out.println("Start Advertising...\n");
        //     update();
        //     sendAlertSSLMessage(emailFromAddress, reading.recipients,
        //                         "Emergency Alert from " + sup + " backed by " + auxs, note);
        //     System.out.println("Data Advertised\n");
        //     break;

        case "Confirm":
            System.out.println("Connect to SISServer successful.");
            break;
        case "Setting":
            if (receiver.equals(NAME))
            {
                System.out.println("Message from " + sender);
                System.out.println("Message type: " + messageType);
                System.out.println("Message Purpose: " + purpose);
                switch (purpose) {
                        case "Activate":
                            // TODO: put your logic code here after the activation

                            System.out.println("Algorithm Activated");
                            break;
                        // TODO: optionally, you can define your message here

                        case "Kill":
                            try {
                                //timer.cancel();
                            } catch (Exception e) {
                                // TODO: handle exception
                            }
                            System.exit(0);
                            break;
                        case "SwitchUser":
                            String user = kvList.getValue("UserID");
                            reading.uid = user;
                            System.out.println("User Switched: "+user);
                            switcha();
                            break;
                        case "UpdateRecipients":
                            String recs = kvList.getValue("Recipients");
                            reading.recipients = recs.replaceAll("\\s+", "").split(",",0);
                            System.out.println("Recipients Updated: "+Arrays.toString(reading.recipients)+" "+reading.recipients.length);
                            break;
                        case "ForceUpload":
                            update();
                            break;

            }
            break;
        }
    }
}

    private static void execute(String query) throws Exception {
        String url = "http://ksiresearch.org/chronobot/PHP_Post.php";
        PostQuery.PostToPHP(url, query);
    }

    private static String formQuery(long datetime, String source, String type, Object value){
        return "Insert into records (uid, datetime, source, type, value) values ('"
                        + reading.uid
                        + "',"
                        + "FROM_UNIXTIME("+datetime/1000+")"
                        + ",'"
                        + source
                        + "','"
                        + type
                        + "','"
                        + value.toString()
                        + "')";
    }
    private static String formQuery(String datetime, String source, String type, Object value, String originator){
        String q = "Insert into records (uid, datetime, source, type, value) values ('"
                        + reading.uid
                        + "','"
                        + datetime
                        + "','"
                        + source
                        + "','"
                        + type
                        + "','"
                        + value.toString()
                        + "','"
                        +originator
                        + "')";
        System.out.println(q);
        return q;
    }

    //@Overload to add Originator
    private static String formQuery(long datetime, String source, String type, Object value, String originator){
        return "Insert into records (uid, datetime, source, type, value, originator) values ('"
                        + reading.uid
                        + "',"
                        + "FROM_UNIXTIME("+datetime/1000+")"
                        + ",'"
                        + source
                        + "','"
                        + type
                        + "','"
                        + value.toString()
                        + "','"
                        +originator
                        + "')";
    }


    private static void switcha() throws Exception{
        // uid ip password email firstname lastname
        System.out.println("User Log in...");
        String query = 
            "UPDATE users " +
            "SET ip='" + NetTool.getPublicAddress() + "' " +
            "WHERE uid='" + reading.uid + "'";
        execute(query);
        System.out.println("User Logged In");
    }

    private static void update() throws Exception{

        System.out.println(reading.toString());

        System.out.println("Updating DB...");
        switch(reading.up) {
            case "SocialNetwork":
                int id = Integer.valueOf(reading.originator);
                boolean isVote = group.vote(id);
                if(!isVote) break;
                System.out.println("passed the predicate and vote now")
                execute(formQuery(reading.dateChiSensor,reading.up,"tongue",reading.tongue, reading.originator));
                execute(formQuery(reading.dateChiSensor,reading.up,"fatigue",reading.fatigue, reading.originator));
                execute(formQuery(reading.dateChiSensor,reading.up,"weakBreadth",reading.weakBreadth, reading.originator));
                execute(formQuery(reading.dateChiSensor,reading.up,"pulse",reading.pulse, reading.originator));
                execute(formQuery(reading.dateChiSensor,reading.up,"sweaty",reading.sweaty, reading.originator));
                execute(formQuery(reading.dateChiSensor,reading.up,"chiTotal",reading.chiTotal, reading.originator));
                group.increase(id);
                break;
            case "ChiMonitor":


                //execute(formQuery(reading.dateVotes,"SocialNetwork","votes",reading.votes));
                if (reading.purpose.equals("update")) {
                    // Colin
                    execute(formQuery(reading.dateChiSensor,reading.up,"tongue",reading.tongue, reading.originator));
                    execute(formQuery(reading.dateChiSensor,reading.up,"fatigue",reading.fatigue, reading.originator));
                    execute(formQuery(reading.dateChiSensor,reading.up,"weakBreadth",reading.weakBreadth, reading.originator));
                    execute(formQuery(reading.dateChiSensor,reading.up,"pulse",reading.pulse, reading.originator));
                    execute(formQuery(reading.dateChiSensor,reading.up,"sweaty",reading.sweaty, reading.originator));
                    execute(formQuery(reading.dateChiSensor,reading.up,"chiTotal",reading.chiTotal, reading.originator));
                    // Colin
                }
                else if (reading.purpose.equals("analysis")){
                    System.out.println("++++++++++++++++++++");
                    System.out.println("M5 Update");
                    System.out.println("++++++++++++++++++++");
                    execute(formQuery(reading.dateChiSensor,"Analysis","tongue",reading.tongue, reading.originator));
                    execute(formQuery(reading.dateChiSensor,"Analysis","fatigue",reading.fatigue, reading.originator));
                    execute(formQuery(reading.dateChiSensor,"Analysis","weakBreadth",reading.weakBreadth, reading.originator));
                    execute(formQuery(reading.dateChiSensor,"Analysis","pulse",reading.pulse, reading.originator));
                    execute(formQuery(reading.dateChiSensor,"Analysis","sweaty",reading.sweaty, reading.originator));
                    execute(formQuery(reading.dateChiSensor,"Analysis","chiTotal",reading.chiTotal, reading.originator));
                    // Colin
                }

                break;
            case "ChiWebGUI":
                // update database here
                // Colin
                for (int i = 0; i < reading.records.size(); i++) {
                    execute(formQuery(reading.GUIDate + (long) (i*1000),"Similar","uid",reading.records.get(i).get("uid"), reading.originator));
                    execute(formQuery(reading.GUIDate + (long) (i*1000),"Similar","datetime",reading.records.get(i).get("datetime"), reading.originator));
                    execute(formQuery(reading.GUIDate + (long) (i*1000),"Similar","source",reading.records.get(i).get("source"), reading.originator));
                    execute(formQuery(reading.GUIDate + (long) (i*1000),"Similar","tongue",reading.records.get(i).get("tongue"), reading.originator));
                    execute(formQuery(reading.GUIDate + (long) (i*1000),"Similar","fatigue",reading.records.get(i).get("fatigue"), reading.originator));
                    execute(formQuery(reading.GUIDate + (long) (i*1000),"Similar","weakBreadth",reading.records.get(i).get("weakBreadth"), reading.originator));
                    execute(formQuery(reading.GUIDate + (long) (i*1000),"Similar","pulse",reading.records.get(i).get("pulse"), reading.originator));
                    execute(formQuery(reading.GUIDate + (long) (i*1000),"Similar","sweaty",reading.records.get(i).get("sweaty"), reading.originator));
                    execute(formQuery(reading.GUIDate + (long) (i*1000),"Similar","chiTotal",reading.records.get(i).get("chiTotal"), reading.originator));
                    execute(formQuery(reading.GUIDate + (long) (i*1000),"Similar","originator",reading.records.get(i).get("originator"), reading.originator));
                }
                
                // Colin
                break;
        }
        

        // execute(formQuery(reading.dateSPO2,"SPO2","spo2",reading.spo2));
        // execute(formQuery(reading.dateBP,"BloodPressure","systolic",reading.systolic));
        // execute(formQuery(reading.dateBP,"BloodPressure","diastolic",reading.diastolic));
        // execute(formQuery(reading.dateBP,"BloodPressure","pulse",reading.pulse));
        // execute(formQuery(reading.dateEKG,"EKG","ekg",reading.ekg));
        // //execute(formQuery(reading.dateTemp,"Temperature","temp",reading.temp));
        
        System.out.println("DB Updated");
        // sendSSLMessage(sendTo, emailSubjectTxt, emailMsgTxt,
        // emailFromAddress, lname, fname, spo2);
    }
}

class UploaderReading
{
    String uid = "376896";
    String firstName = "Shi-Kuo";
    String lastName = "Chang";
    String[] recipients = { "sisfortest@outlook.com",
                            "chronobot@ksiresearch.org"
                          };
    // int spo2;
    // int systolic;
    // int diastolic;
    // int pulse;
    // int ekg;
    // long dateBP;
    // long dateEKG;
    // long dateSPO2;
    //double temp;
    //long dateTemp;
    // String kinectStatus;
    // long dateKinect;
    String votes = "";
    long dateVotes;

    long dateChiSensor;
    int tongue;
    int fatigue;
    int weakBreadth;
    int pulse;
    int sweaty;
    String originator;
    String chiTotal;
    String up = ""; // use this var to indicate what to upload. 
    String purpose = "";
    String sim = "";
    String ssource = "";
    long GUIDate;
    // Colin
    ArrayList<HashMap<String, String>> records = new ArrayList<HashMap<String, String>>();
    HashMap<String, String> record = new HashMap<String, String>();
    // Colin
    //double score;

    @Override
    public String toString()
    {
        // TODO Auto-generated method stub
        StringBuilder builder = new StringBuilder();
        builder.append("----------------------------------------------\n");
        builder.append("First Name: " + firstName + "\n");
        builder.append("Last Name: " + lastName + "\n");
        builder.append("Email: " + Arrays.toString(recipients) + "\n\n");
        builder.append("Fatigue: " + fatigue + "\n");
        builder.append("UserID: " + uid + "\n");
        builder.append("ChiTotal: " + chiTotal + "\n");
        // builder.append("Date (Votes): " + dateVotes + "\n");
        // builder.append("Systolic: " + systolic + "\n");
        // builder.append("Diastolic: " + diastolic + "\n");
        // builder.append("Pulse: " + pulse + "\n");
        // builder.append("Date (Blood Pressure): " + dateBP + "\n\n");
        // builder.append("EKG: " + ekg + "\n");
        // builder.append("Date (EKG): " + dateEKG + "\n\n");
        // builder.append("SPO2: " + spo2 + "\n");
        // builder.append("Date (SPO2): " + dateSPO2 + "\n\n");
        // //builder.append("Temperature: " + temp + "\n");
        // //builder.append("Date (Temperature): " + dateTemp + "\n\n");
        // builder.append("Kinect Status: " + kinectStatus + "\n");
        // builder.append("Date (Kinect): " + dateKinect + "\n");
        builder.append("----------------------------------------------\n");
        return builder.toString();
    }
}