import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;



public class CreateSocialNetworkSensor {

    // socket for connection to SISServer
    static Socket universal;
    private static int port = 53217;
    // message writer
    static MsgEncoder encoder;
    // message reader
    static MsgDecoder decoder;
    // scope of this component
    private static final String SCOPE = "SIS.Chi";
    // name of this component
    private static final String NAME = "SocialNetworkSensor";
    // messages types that can be handled by this component
    private static final List<String> TYPES = new ArrayList<String>(
            Arrays.asList(new String[]{"Setting", "Confirm"}));

    private static int tongue = 0, fatigue = 0, weakBreadth = 0, pulse = 0, sweaty = 0;
    private static Date startDate = new Date(), endDate = new Date();

    private static Timer timer = new Timer();

    // shared by all kinds of records that can be generated by this component
    private static KeyValueList record = new KeyValueList();
    // shared by all kinds of alerts that can be generated by this component
    private static KeyValueList alert = new KeyValueList();

    private static ChiReading reading = new ChiReading();

    private static SimpleDateFormat format = new SimpleDateFormat(
            "yyyy-MM-dd HH:mm:ss");

    private static int count = 0;

    /*
     * Main program
     */
    public static void main(String[] args) {
        while (true) {
            try {

                // try to establish a connection to SISServer
                universal = connect();

                // bind the message reader to inputstream of the socket
                decoder = new MsgDecoder(universal.getInputStream());
                // bind the message writer to outputstream of the socket
                encoder = new MsgEncoder(universal.getOutputStream());

                /*
                 * construct a Connect message to establish the connection
                 */
                KeyValueList conn = new KeyValueList();
                conn.putPair("Scope", SCOPE);
                conn.putPair("MessageType", "Connect");
                conn.putPair("Role", "Basic");
                conn.putPair("Name", NAME);
                encoder.sendMsg(conn);

                initRecord();

                // KeyValueList for inward messages, see KeyValueList for
                // details
                KeyValueList kvList;

                while (true) {
                    // attempt to read and decode a message, see MsgDecoder for
                    // details


                // dummy message
                   kvList = decoder.getMsg();
                    // kvList = new KeyValueList();
                    // kvList.putPair("MessageType", "Setting");
                    // kvList.putPair("Scope", "SIS.Chi");
                    // kvList.putPair("Sender", "ChiGUI");
                    // kvList.putPair("Receiver", "ChiSensor");
                    // kvList.putPair("Purpose", "Activate");

                    // process that message
                    ProcessMsg(kvList);
                }

            } catch (Exception e) {
                // if anything goes wrong, try to re-establish the connection
                e.printStackTrace();
                try {
                    // wait for 1 second to retry
                    Thread.sleep(1000);
                } catch (InterruptedException e2) {
                }
                System.out.println("Try to reconnect");
                try {
                    universal = connect();
                } catch (IOException e1) {
                }
            }
        }
    }

    /*
     * used for connect(reconnect) to SISServer
     */
    static Socket connect() throws IOException {
        Socket socket = new Socket("127.0.0.1", port);
        return socket;
    }

    private static void initRecord() {
        record.putPair("Scope", SCOPE);
        record.putPair("MessageType", "Reading");
        record.putPair("Sender", NAME);

        // Receiver may be different for each message, so it doesn't make sense
        // to set here
        // record.putPair("Receiver", "");

        alert.putPair("Scope", SCOPE);
        alert.putPair("MessageType", "Alert");
        alert.putPair("Sender", NAME);
        alert.putPair("Purpose", "ChiAlert");

        // Receiver may be different for each message, so it doesn't make sense
        // to set here
        // alert.putPair("Receiver", "");
    }

    private static void componentTask() {
        try {
            // dummyCollect();
            collect();
            reading.date = System.currentTimeMillis();
            //reading
            record.putPair("uid", reading.uid + "");
            record.putPair("tongue", reading.tongue + "");
            record.putPair("fatigue", reading.fatigue + "");
            record.putPair("weakBreadth", reading.weakBreadth + "");
            record.putPair("pulse", reading.pulse + "");
            record.putPair("sweaty", reading.sweaty + "");
            record.putPair("datetime", reading.date + "");
            //send reading message to GUI, uploader
            //encoder.sendMsg(record);
            //send reading message to controller
            // record.putPair("Receiver", "ChiController");
            // send to chiMonitor
            record.putPair("Receiver", "SocialNetwork");
            record.putPair("Originator",reading.originator+"");
            record.putPair("ChiTotal","N");
            record.putPair("Purpose","Reading");
            record.putPair("MessageType","Reading");
            encoder.sendMsg(record);
            record.removePair("Receiver");
            encoder.sendMsg(record);
            
            // if (reading.temp > min && reading.temp < max) {//normal
            //     //reading
            //     reading.date = System.currentTimeMillis();
            //     record.putPair("Temp", reading.temp + "");
            //     record.putPair("Date", reading.date + "");
            //     //send reading message to GUI, uploader
            //     encoder.sendMsg(record);
            //     //send reading message to controller
            //     record.putPair("Receiver", "DiController1");
            //     encoder.sendMsg(record);
            //     record.removePair("Receiver");
            // } else { //alert
            //     alert.putPair("Temp", reading.temp + "");
            //     alert.putPair("Date", reading.date + "");
            //     //send alert message to GUI, uploader
            //     encoder.sendMsg(alert);
            //     //send alert message to controller
            //     alert.removePair("Receiver");
            //     alert.putPair("Receiver", "DiController1");
            //     encoder.sendMsg(alert);
            // }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private static void ProcessMsg(KeyValueList kvList) throws Exception {

        String scope = kvList.getValue("Scope");
        if (!SCOPE.startsWith(scope)) {
            return;
        }

        String messageType = kvList.getValue("MessageType");
        if (!TYPES.contains(messageType)) {
            return;
        }

        String sender = kvList.getValue("Sender");

        String receiver = kvList.getValue("Receiver");

        String purpose = kvList.getValue("Purpose");

        switch (messageType) {
            case "Confirm":
                System.out.println("Connect to SISServer successful.");
                break;
            case "Setting":
                if (receiver.equals(NAME)) {
                    System.out.println("Message from " + sender);
                    System.out.println("Message type: " + messageType);
                    System.out.println("Message Purpose: " + purpose);
                    switch (purpose) {

                        case "Activate":
                            componentTask();
                            break;

                        case "Kill":
                            try {
                                timer.cancel();
                            } catch (Exception e) {
                                // TODO: handle exception
                            }
                            System.exit(0);
                            break;

                        case "Deactivate":
                            try {
                                timer.cancel();
                            } catch (Exception e) {
                                // TODO: handle exception
                            }
                            System.out.println("Algorithm Deactivated");
                            break;
                    }
                }
                break;
        }
    }


    // private static void dummyCollect() throws Exception {
    //     double[] temps = {24.64, 25.25, 27.59, 24.35};
    //     reading.temp = temps[count++ % temps.length];
    //     System.out.println(reading.temp);
    // }

    private static void collect() throws Exception {
        //reading.score = 100.0;
        System.out.println("Plase Enter User ID:");
        reading.uid = Integer.parseInt(System.console().readLine());
        System.out.println("Plase Enter value for tongue:");
        reading.tongue = Integer.parseInt(System.console().readLine());
        System.out.println("Plase Enter value for fatigue:");
        reading.fatigue = Integer.parseInt(System.console().readLine());
        System.out.println("Plase Enter value for weakBreadth:");
        reading.weakBreadth = Integer.parseInt(System.console().readLine());
        System.out.println("Plase Enter value for pulse:");
        reading.pulse = Integer.parseInt(System.console().readLine());
        System.out.println("Plase Enter value for sweaty:");
        reading.sweaty = Integer.parseInt(System.console().readLine());
        System.out.println("Plase Enter Originator:");
        reading.originator = Integer.parseInt(System.console().readLine());
        System.out.println(reading.uid);
        System.out.println(reading.tongue);
        System.out.println(reading.fatigue);
        System.out.println(reading.weakBreadth);
        System.out.println(reading.pulse);
        System.out.println(reading.sweaty);
        System.out.println(reading.originator);
    }
}

class ChiReading {
    int tongue;
    int fatigue;
    int weakBreadth;
    int pulse;
    int sweaty;
    //double score;
    long date;
    int uid;
    int originator;
}
