import java.io.IOException;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;

public class CreateBloodPressure {
	// socket for connection to SISServer
	private static Socket universal;
	private static int port = 53217;
	// message writer
	private static MsgEncoder encoder;
	// message reader
	private static MsgDecoder decoder;
	// scope of this component
	private static final String SCOPE = "SIS.Ren";
	// name of this component
    private static final String NAME = "BloodPressure";
	// messages types that can be handled by this component
	
	private static final List<String> TYPES = new ArrayList<String>(
			Arrays.asList(new String[] { "Setting", "Confirm" }));

	private static int refreshRate = 500, max = 140, min = 90;
	private static Date startDate = new Date(), endDate = new Date();

	private static Timer timer = new Timer();

	// shared by all kinds of records that can be generated by this component
	private static KeyValueList record = new KeyValueList();
	// shared by all kinds of alerts that can be generated by this component
	private static KeyValueList alert = new KeyValueList();

	private static BPReading reading = new BPReading();

	/*
	 * Main program
	 */
	public static void main(String[] args) {
		while (true) {
			try {
				// try to establish a connection to SISServer
				universal = connect();

				// bind the message reader to inputstream of the socket
				decoder = new MsgDecoder(universal.getInputStream());
				// bind the message writer to outputstream of the socket
				encoder = new MsgEncoder(universal.getOutputStream());

				/*
				 * construct a Connect message to establish the connection
				 */
				KeyValueList conn = new KeyValueList();
				conn.putPair("Scope", SCOPE);
				conn.putPair("MessageType", "Connect");
				conn.putPair("Role", "Basic");
				conn.putPair("Name", NAME);
				encoder.sendMsg(conn);

				initRecord();

				// componentTask();

				// KeyValueList for inward messages, see KeyValueList for
				// details
				KeyValueList kvList;

				while (true) {
					// attempt to read and decode a message, see MsgDecoder for
					// details
					kvList = decoder.getMsg();

					// process that message
					ProcessMsg(kvList);
				}

			} catch (Exception e) {
				// if anything goes wrong, try to re-establish the connection
				e.printStackTrace();
				try {
					// wait for 1 second to retry
					Thread.sleep(1000);
				} catch (InterruptedException e2) {
				}
				System.out.println("Try to reconnect");
				try {
					universal = connect();
				} catch (IOException e1) {
				}
			}
		}
	}

	/*
	 * used for connect(reconnect) to SISServer
	 */
	private static Socket connect() throws IOException {
		Socket socket = new Socket("127.0.0.1", port);
		return socket;
	}

	private static void initRecord() {
		record.putPair("Scope", SCOPE);
		record.putPair("MessageType", "Reading");
		record.putPair("Sender", NAME);

		// Receiver may be different for each message, so it doesn't make sense
		// to set here
		// record.putPair("Receiver", "");

		alert.putPair("Scope", SCOPE);
		alert.putPair("MessageType", "Alert");
		alert.putPair("Sender", NAME);
		alert.putPair("Purpose", "BloodPressureAlert");

		// Receiver may be different for each message, so it doesn't make sense
		// to set here
		// alert.putPair("Receiver", "");
	}

	private static void componentTask() {
		try {
			
			if (reading.systolic > min && reading.diastolic < max) {
				record.putPair("Systolic", reading.systolic + "");
				record.putPair("Diastolic", reading.diastolic + "");
				record.putPair("Pulse", reading.pulse + "");
				record.putPair("Date", reading.date + "");
				//send reading message to GUI, uploader
				encoder.sendMsg(record);
				//send reading message to controller
				record.putPair("Receiver", "RenController");
				encoder.sendMsg(record);
				record.removePair("Receiver");
			} else {
				alert.putPair("Systolic", reading.systolic + "");
				alert.putPair("Diastolic", reading.diastolic + "");
				alert.putPair("Pulse", reading.pulse + "");
				alert.putPair("Date", reading.date + "");
				//send alert message to GUI, uploader
                encoder.sendMsg(alert);
				//send alert message to controller
				alert.removePair("Receiver");
				alert.putPair("Receiver", "RenController");
                encoder.sendMsg(alert);
			}

		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private static void ProcessMsg(KeyValueList kvList) throws Exception {

		String scope = kvList.getValue("Scope");
		if (!SCOPE.startsWith(scope)) {
			return;
		}

		String messageType = kvList.getValue("MessageType");
		if (!TYPES.contains(messageType)) {
			return;
		}

		String sender = kvList.getValue("Sender");

		String receiver = kvList.getValue("Receiver");

		String purpose = kvList.getValue("Purpose");

		switch (messageType) {
		case "Confirm":
			System.out.println("Connect to SISServer successful.");
			break;
		case "Setting":
			if (receiver.equals(NAME)) {

				//System.out.println(kvList);
				// System.out.println("Message from " + sender);
				// System.out.println("Message type: " + messageType);
				// System.out.println("Message Purpose: " + purpose);
				switch (purpose) {

				case "Activate":
					String rRate = kvList.getValue("RefreshRate");
					String sDate = kvList.getValue("StartDate");
					String eDate = kvList.getValue("EndDate");
					String maxx = kvList.getValue("Max");
					String minn = kvList.getValue("Min");

					if (rRate != null && !rRate.equals("")) {

						refreshRate = Integer.parseInt(rRate);
					}

					if (sDate != null && !sDate.equals("") && eDate != null
							&& !eDate.equals("")) {
						startDate.setTime(Long.parseLong(sDate));
						endDate.setTime(Long.parseLong(eDate));
					}

					if (maxx != null && !maxx.equals("") && minn != null
							&& !minn.equals("")) {
						max = Integer.parseInt(maxx);
						min = Integer.parseInt(minn);
					}
					try {
						timer.cancel();
						timer = new Timer();
					} catch (Exception e) {
						// TODO: handle exception
					}
					timer.schedule(new TimerTask() {

						@Override
						public void run() {
							// TODO Auto-generated method stub
							if (System.currentTimeMillis() - endDate.getTime() > 0) {
								cancel();
							} else {
								componentTask();
							}
						}
					}, startDate, refreshRate);
					System.out.println("Algorithm Activated");
					break;

				// case "AdjustRefreshRate":
				// String rRate = kvList.getValue("RefreshRate");
				// if (rRate != null && !rRate.equals("")) {
				// timer.cancel();
				// timer.purge();
				// refreshRate = Integer.parseInt(rRate);
				// timer.schedule(new TimerTask() {
				//
				// @Override
				// public void run() {
				// // TODO Auto-generated method stub
				// componentTask();
				// }
				// }, startDate, refreshRate);
				// }
				//
				// break;
				// case "AdjustDateRange":
				// String sDate = kvList.getValue("StartDate");
				// String eDate = kvList.getValue("EndDate");
				// if (sDate != null && !sDate.equals("") && eDate != null
				// && !eDate.equals("")) {
				// timer.cancel();
				// timer.purge();
				// startDate.setTime(Long.parseLong(sDate));
				// endDate.setTime(Long.parseLong(eDate));
				// timer.schedule(new TimerTask() {
				//
				// @Override
				// public void run() {
				// // TODO Auto-generated method stub
				// componentTask();
				// }
				// }, startDate, refreshRate);
				// }
				//
				// break;
				// case "AdjustThreshold":
				// String maxx = kvList.getValue("Max");
				// String minn = kvList.getValue("Min");
				// if (maxx != null && !maxx.equals("") && minn != null
				// && !minn.equals("")) {
				// timer.cancel();
				// timer.purge();
				// max = Integer.parseInt(maxx);
				// min = Integer.parseInt(minn);
				// timer.schedule(new TimerTask() {
				//
				// @Override
				// public void run() {
				// // TODO Auto-generated method stub
				// componentTask();
				// }
				// }, startDate, refreshRate);
				// }
				// break;

				case "UpdateRecord":
					String sys = kvList.getValue("Systolic");
					String dia = kvList.getValue("Diastolic");
					String pul = kvList.getValue("Pulse");
					String dat = kvList.getValue("Date");

					if (sys != null && !sys.equals("")) {
						reading.systolic = Integer.parseInt(sys);
					}
					if (dia != null && !dia.equals("")) {
						reading.diastolic = Integer.parseInt(dia);
					}
					if (pul != null && !pul.equals("")) {
						reading.pulse = Integer.parseInt(pul);
					}
					if (dat != null && !dat.equals("")) {
						reading.date = Long.parseLong(dat);
					}

					break;

				case "Kill":
					try {
						timer.cancel();
					} catch (Exception e) {
						// TODO: handle exception
					}
					System.exit(0);
					break;
				// case "Activate":
				// try {
				// timer.cancel();
				// timer = new Timer();
				// } catch (Exception e) {
				// // TODO: handle exception
				// }
				// timer.schedule(new TimerTask() {
				//
				// @Override
				// public void run() {
				// // TODO Auto-generated method stub
				// if (System.currentTimeMillis() - endDate.getTime() > 0) {
				// cancel();
				// } else {
				// componentTask();
				// }
				// }
				// }, startDate, refreshRate);
				// System.out.println("Algorithm Activated");
				// break;
				case "Deactivate":
					try {
						timer.cancel();
					} catch (Exception e) {
						// TODO: handle exception
					}
					System.out.println("Algorithm Deactivated");
					break;
				}
			}
			break;
		}
	}
}

class BPReading {
	int systolic;
	int diastolic;
	int pulse;
	long date;
}
