import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import java.util.HashSet;
import javax.xml.parsers.*;
import org.xml.sax.InputSource;
import org.w3c.dom.*;
import java.io.*;



public class CreateChiWebGUI {

    // socket for connection to SISServer
    static Socket universal;
    private static int port = 53217;
    // message writer
    static MsgEncoder encoder;
    // message reader
    static MsgDecoder decoder;
    // scope of this component
    private static final String SCOPE = "SIS.Chi";
    // name of this component
    private static final String NAME = "ChiWebGUI";
    // messages types that cWebGUIan be handled by this component
    private static final List<String> TYPES = new ArrayList<String>(
            Arrays.asList(new String[]{"Setting", "Confirm","Reading"}));

    //private static int tongue = 0, fatigue = 0, weakBreadth = 0, pulse = 0, sweaty = 0;
    private static Date startDate = new Date(), endDate = new Date();

    private static int refreshRate = 5000;

    private static Timer timer = new Timer();

    // shared by all kinds of records that can be generated by this component
    private static KeyValueList record = new KeyValueList();
    // shared by all kinds of alerts that can be generated by this component
    private static KeyValueList alert = new KeyValueList();

    //private static ChiReading reading = new ChiReading();

    private static SimpleDateFormat format = new SimpleDateFormat(
            "yyyy-MM-dd HH:mm:ss");

    private static int count = 0;

    /*
     * Main program
     */
    public static void main(String[] args) {
        while (true) {
            try {

                // try to establish a connection to SISServer
                universal = connect();

                // bind the message reader to inputstream of the socket
                decoder = new MsgDecoder(universal.getInputStream());
                // bind the message writer to outputstream of the socket
                encoder = new MsgEncoder(universal.getOutputStream());

                /*
                 * construct a Connect message to establish the connection
                 */
                KeyValueList conn = new KeyValueList();
                conn.putPair("Scope", SCOPE);
                conn.putPair("MessageType", "Connect");
                conn.putPair("Role", "Basic");
                conn.putPair("Name", NAME);
                encoder.sendMsg(conn);

                initRecord();

                // KeyValueList for inward messages, see KeyValueList for
                // details
                KeyValueList kvList;

                while (true) {
                    // attempt to read and decode a message, see MsgDecoder for
                    // details


                // dummy message
                   kvList = decoder.getMsg();
                    // kvList = new KeyValueList();
                    // kvList.putPair("MessageType", "Setting");
                    // kvList.putPair("Scope", "SIS.Chi");
                    // kvList.putPair("Sender", "ChiGUI");
                    // kvList.putPair("Receiver", "ChiSensor");
                    // kvList.putPair("Purpose", "Activate");

                    // process that message
                    ProcessMsg(kvList);
                }

            } catch (Exception e) {
                // if anything goes wrong, try to re-establish the connection
                e.printStackTrace();
                try {
                    // wait for 1 second to retry
                    Thread.sleep(1000);
                } catch (InterruptedException e2) {
                }
                System.out.println("Try to reconnect");
                try {
                    universal = connect();
                } catch (IOException e1) {
                }
            }
        }
    }

    /*
     * used for connect(reconnect) to SISServer
     */
    static Socket connect() throws IOException {
        Socket socket = new Socket("127.0.0.1", port);
        return socket;
    }

    private static void initRecord() {
        record.putPair("Scope", SCOPE);
        record.putPair("MessageType", "Reading");
        record.putPair("Sender", NAME);

        // Receiver may be different for each message, so it doesn't make sense
        // to set here
        // record.putPair("Receiver", "");

        alert.putPair("Scope", SCOPE);
        alert.putPair("MessageType", "Alert");
        alert.putPair("Sender", NAME);
        alert.putPair("Purpose", "ChiAlert");

        // Receiver may be different for each message, so it doesn't make sense
        // to set here
        // alert.putPair("Receiver", "");
    }

    private static void componentTask() {
        try {
            timer.schedule(new TimerTask(){
                @Override
                public void run() {
                    Data data = new Data("messages",
                            "Select * From messages where readid='0' and messagetype='M3'or readid='0' and messagetype='M10' or readid='0' and messagetype='M5' order by mid desc limit 1");
                    if (data.size() > 0) {
                        String xmlmsg = data.getRecord(0, 3);

                        record.putPair("uid", data.getRecord(0, "uid") + "");
                        //record.putPair("datetime", data.getRecord(0, "datetime"));
                        record.putPair("tongue", data.getRecord(0, "tongue") + "");
                        record.putPair("fatigue", data.getRecord(0, "fatigue") + "");
                        record.putPair("weakBreadth", data.getRecord(0, "weakBreadth") + "");
                        record.putPair("pulse", data.getRecord(0, "pulse") + "");
                        record.putPair("sweaty", data.getRecord(0, "sweaty") + "");
                        record.putPair("datetime", System.currentTimeMillis() + "");
                        record.putPair("MessageType","Reading");

                        try{
                            record.putPair("originator", data.getRecord(0, "originator"));
                            // record.putPair("Target", getTarget(xmlmsg));
                        }
                        catch(Exception e) {
                            e.printStackTrace();
                        }
                        // m5 send to socialnetworksensor, m3 send to chiuploader
                        if (data.getRecord(0, "messagetype").equals("M10")) {
                            record.putPair("Receiver", "SocialNetwork");
                            try{
                                record.putPair("Target", getTarget(xmlmsg));
                            // record.putPair("Target", getTarget(xmlmsg));
                            }
                            catch(Exception e) {
                                e.printStackTrace();
                            }
                            System.out.println("Sent msg to SocialNetwork");
                        } else if (data.getRecord(0, "messagetype").equals("M3")) {
                            // record.putPair("uid", data.getRecord(0, "uid") + "");
                            record.putPair("Receiver", "ChiUploader");
                            System.out.println("Sent msg to ChiUploader");
                        }
                        else if (data.getRecord(0, "messagetype").equals("M5")) {
                            // record.putPair("uid", data.getRecord(0, "uid") + "");
                            record.putPair("Receiver", "ChiMonitor");
                            System.out.println("Sent msg to ChiMonitor");
                        }
                        
                        // set the read id from 0 to 1
                        String mid = data.getRecord(0, "mid");

                        System.out.println("--------------------------------");
                        System.out.println(mid);
                        System.out.println("--------------------------------");

                        String mChange = "UPDATE messages SET readid='1' WHERE readid='0' and mid='" + mid + "'";

                        try {
                            //System.out.println("Sent msg to ChiUploader");
                            System.out.println(record.toString());
                            encoder.sendMsg(record);
                            record.removePair("Receiver");
                            encoder.sendMsg(record);
                            execute(mChange);
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    } else {
                        System.out.println("No M3 or M10 detected from Messages");
                    }
                }
            }, refreshRate);    

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static String getOriginator(String xml)throws Exception {
        try{
            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance().newInstance();
            DocumentBuilder db = dbf.newDocumentBuilder();
            InputSource is = new InputSource();
            is.setCharacterStream(new StringReader(xml));

            Document doc = db.parse(is);
            NodeList nodes = doc.getElementsByTagName("Item");

            for(int i = 0; i < nodes.getLength(); i++){
                Element element = (Element) nodes.item(i);
                NodeList name = element.getElementsByTagName("Key");
                Element line = (Element) name.item(0);
                if(line.getFirstChild().getTextContent().equals("Originator")) {
                    NodeList title = element.getElementsByTagName("Value");
                    line = (Element) title.item(0);
                    return line.getFirstChild().getTextContent();
                }
            }
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        return "";
    }

        public static String getTarget(String xml)throws Exception {
        try{
            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance().newInstance();
            DocumentBuilder db = dbf.newDocumentBuilder();
            InputSource is = new InputSource();
            is.setCharacterStream(new StringReader(xml));

            Document doc = db.parse(is);
            NodeList nodes = doc.getElementsByTagName("Item");

            for(int i = 0; i < nodes.getLength(); i++){
                Element element = (Element) nodes.item(i);
                NodeList name = element.getElementsByTagName("Key");
                Element line = (Element) name.item(0);
                if(line.getFirstChild().getTextContent().equals("Target")) {
                    NodeList title = element.getElementsByTagName("Value");
                    line = (Element) title.item(0);
                    return line.getFirstChild().getTextContent();
                }
            }
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        return "";
    }

    private static void execute(String query) throws Exception {
        String url = "http://ksiresearch.org/chronobot/PHP_Post.php";
        PostQuery.PostToPHP(url, query);
    }

    private static void ProcessMsg(KeyValueList kvList) throws Exception {

        String scope = kvList.getValue("Scope");
        if (!SCOPE.startsWith(scope)) {
            return;
        }

        String messageType = kvList.getValue("MessageType");
        if (!TYPES.contains(messageType)) {
            return;
        }

        String sender = kvList.getValue("Sender");

        String receiver = kvList.getValue("Receiver");

        String purpose = kvList.getValue("Purpose");

        switch (messageType) {
            case "Confirm":
                System.out.println("Connect to SISServer successful.");
                break;
            case "Setting":
                if (receiver.equals(NAME)) {
                    System.out.println("Message from " + sender);
                    System.out.println("Message type: " + messageType);
                    System.out.println("Message Purpose: " + purpose);
                    switch (purpose) {

                        case "Activate":
                            timer.schedule(new TimerTask() {
                                @Override
                                public void run() {
                                    // TODO Auto-generated method stub
                                    componentTask();
                                    
                                }
                            }, startDate, refreshRate);
                            break;

                        case "Kill":
                            try {
                                timer.cancel();
                            } catch (Exception e) {
                                // TODO: handle exception
                            }
                            System.exit(0);
                            break;

                        case "Deactivate":
                            try {
                                timer.cancel();
                            } catch (Exception e) {
                                // TODO: handle exception
                            }
                            System.out.println("Algorithm Deactivated");
                            break;
                    }
                }
                break;
        }
    }


    // private static void dummyCollect() throws Exception {
    //     double[] temps = {24.64, 25.25, 27.59, 24.35};
    //     reading.temp = temps[count++ % temps.length];
    //     System.out.println(reading.temp);
    // }


}

