import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.StringTokenizer;
import java.util.*;
import java.io.*;
import java.net.*;
import java.lang.*;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

public class CreateFlowerManager {
	
	// socket for connection to SISServer
	private static Socket universal;
	private static int port = 53217;
	// message writer
	private static MsgEncoder encoder;
	// message reader
	private static MsgDecoder decoder;
	
	// scope of this component
	private static final String SCOPE = "SIS.Tien";
	// name of this component
	private static final String NAME = "FlowerManager";
	// messages types that can be handled by this component
	private static final List<String> TYPES = new ArrayList<String>(
			Arrays.asList(new String[] { "Setting", "Reading", "Alert", "Confirm" }));

	// summary for all incoming / outgoing messages
	private static final String incomingMessages = "IN\tConfirm|Setting:Kill||Alert:FlowerPowerAlert|Alert:FlowerPowerAlert2";
	private static final String outgoingMessages = "OUT\t Connect|Emergency";

	// shared by all kinds of emergencies that can be generated by this component
	// private static KeyValueList emergency = new KeyValueList();

	private static StateMachine stateMachine;
	
	private static KeyValueList alert = new KeyValueList();
		
	private static ArrayList<FlowerManagerReading> readings = new ArrayList<FlowerManagerReading>();
	
	private static String temperature=null;
	private static String fertilizer=null;
	private static String sunshine=null;
	private static String moisture=null;
	private static String dateFP=null;

	/*
	 * Main program
	 */
	public static void main(String[] args) {
		while (true) {
			try {
				// try to establish a connection to SISServer
				universal = connect();

				// bind the message reader to inputstream of the socket
				decoder = new MsgDecoder(universal.getInputStream());
				// bind the message writer to outputstream of the socket
				encoder = new MsgEncoder(universal.getOutputStream());

				//state machine
				stateMachine = new StateMachine(NAME, SCOPE, encoder);

				/*
				 * construct a Connect message to establish the connection
				 */
				KeyValueList conn = new KeyValueList();
				conn.putPair("Scope", SCOPE);
				conn.putPair("MessageType", "Connect");
				conn.putPair("IncomingMessages", incomingMessages);
                conn.putPair("OutgoingMessages", outgoingMessages);
				conn.putPair("Role", "Controller");
				conn.putPair("Name", NAME);
				encoder.sendMsg(conn);

				initRecord();

				// KeyValueList for inward messages, see KeyValueList for
				// details
				KeyValueList kvList;

				while (true) {
					// attempt to read and decode a message, see MsgDecoder for
					// details
					kvList = decoder.getMsg();

					// process that message
					ProcessMsg(kvList);
				}

			} catch (Exception e) {
				// if anything goes wrong, try to re-establish the connection
				try {
					// wait for 1 second to retry
					Thread.sleep(1000);
				} catch (InterruptedException e2) {
				}
				System.out.println("Try to reconnect");
				try {
					universal = connect();
				} catch (IOException e1) {
				}
			}
		}
	}

	/*
	 * used for connect(reconnect) to SISServer
	 */
	static Socket connect() throws IOException {
		Socket socket = new Socket("127.0.0.1", port);
		return socket;
	}
	
	private static void initRecord() {

		// emergency.putPair("Scope", SCOPE);
		// emergency.putPair("MessageType", "Emergency");
		// emergency.putPair("Sender", NAME);

		// Receiver may be different for each message, so it doesn't make sense
		// to set here
		// alert.putPair("Receiver", "RECEIVER");
	}

	/*
	 * process a certain message, execute corresponding actions
	 */
	static void ProcessMsg(KeyValueList kvList) throws IOException {

		String scope = kvList.getValue("Scope");
		
		String broadcast = kvList.getValue("Broadcast");
		String direction = kvList.getValue("Direction");
		
		if(broadcast!=null&&broadcast.equals("True")){
			
			if(direction!=null&&direction.equals("Up")){
				if(!scope.startsWith(SCOPE)){
					return;
				}
			}else if(direction!=null&&direction.equals("Down")){
				if(!SCOPE.startsWith(scope)){
					return;
				}
			}
		}else{
			if(!SCOPE.equals(scope)){
				return;
			}
		}
		
		String messageType = kvList.getValue("MessageType");
		if(!TYPES.contains(messageType)){
			return;
		}
		
		String sender = kvList.getValue("Sender");
		
		String receiver = kvList.getValue("Receiver");
		
		String purpose = kvList.getValue("Purpose");
		
		switch (messageType) {

		// Behaviour
		case "Alert":
			switch (sender) {
			case "FlowerPower2":
				switch (purpose) {
				case "FlowerPowerAlert2":
					System.out.println("FlowerPower2toFlowerManager received, start processing...");
					FlowerReading reading2 = new FlowerReading();
					temperature=kvList.getValue("AirTemperature");
					fertilizer=kvList.getValue("Fertilizer");
					sunshine=kvList.getValue("Light");
					moisture=kvList.getValue("Moisture");
					dateFP=kvList.getValue("Date");
					if (temperature != null && !temperature.equals(""))
					{
						reading2.temperature = Double.parseDouble(temperature);
					}
					else{
						reading2.temperature = 0;
					}
					if (fertilizer != null && !fertilizer.equals(""))
					{
						reading2.fertilizer = Double.parseDouble(fertilizer);
					}
					else{
						reading2.fertilizer = 0;
					}
					if (sunshine != null && !sunshine.equals(""))
					{
						reading2.sunshine = Double.parseDouble(sunshine);
					}
					else{
						reading2.sunshine = 0;
					}
					if (moisture != null && !moisture.equals(""))
					{
						reading2.moisture = Double.parseDouble(moisture);
					}
					else{
						reading2.moisture = 0;
					}
					if (dateFP != null && !dateFP.equals(""))
					{
						reading2.dateFP = Long.parseLong(dateFP);
					}
					else{
						reading2.dateFP = 0;
					}
					
					System.out.println(reading2);
					
					readings.add(new FlowerManagerReading(sender,reading2));

					break;
				}
				break;
			case "FlowerPower":
				switch (purpose) {
				case "FlowerPowerAlert":
					System.out.println("FlowerPower1toFlowerManager received, start processing...");
					FlowerReading reading1 = new FlowerReading();
					temperature=kvList.getValue("AirTemperature");
					fertilizer=kvList.getValue("Fertilizer");
					sunshine=kvList.getValue("Light");
					moisture=kvList.getValue("Moisture");
					dateFP=kvList.getValue("Date");
					if (temperature != null && !temperature.equals(""))
					{
						reading1.temperature = Double.parseDouble(temperature);
					}
					else{
						reading1.temperature = 0;
					}
					if (fertilizer != null && !fertilizer.equals(""))
					{
						reading1.fertilizer = Double.parseDouble(fertilizer);
					}
					else{
						reading1.fertilizer = 0;
					}
					if (sunshine != null && !sunshine.equals(""))
					{
						reading1.sunshine = Double.parseDouble(sunshine);
					}
					else{
						reading1.sunshine = 0;
					}
					if (moisture != null && !moisture.equals(""))
					{
						reading1.moisture = Double.parseDouble(moisture);
					}
					else{
						reading1.moisture = 0;
					}
					if (dateFP != null && !dateFP.equals(""))
					{
						reading1.dateFP = Long.parseLong(dateFP);
					}
					else{
						reading1.dateFP = 0;
					}
					
					System.out.println(reading1);
					
					readings.add(new FlowerManagerReading(sender,reading1));
									//reading.lengthOfData++;

					break;
				}
				break;
			
			}
			break;
		case "Confirm":
			System.out.println("Connect to SISServer successful.");
			break;
		}

		// State
		stateMachine.changeState(messageType, purpose);
	}
	

	
}

class FlowerReading {
	double sunshine;
	double temperature;
	double moisture;
	double fertilizer;
	long dateFP;
	long preDateFP;
	
	public String toString(){
		return	"Sunshine: "	+	sunshine	+ "|" +
				"Temperature: "	+	temperature	+ "|" +
				"Moisture: "	+	moisture	+ "|" +
				"Fertilizer: "	+	fertilizer	+ "|" +
				"DateFP: "		+	dateFP		+ "|" +
				"PreDateFP: "	+	preDateFP	+ "|";
	}
}

class FlowerManagerReading {
	FlowerReading reading;
	String sender;
	
	public FlowerManagerReading(String sender, FlowerReading reading){
		this.reading=reading;
		this.sender=sender;
	}
}
