import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;



public class CreateBCISensor {

    // socket for connection to SISServer
    static Socket universal;
    private static int port = 53217;
    // message writer
    static MsgEncoder encoder;
    // message reader
    static MsgDecoder decoder;
    // scope of this component
    private static final String SCOPE = "SIS.BCI";
    // name of this component
    private static final String NAME = "BCISensor";
    // messages types that can be handled by this component
    private static final List<String> TYPES = new ArrayList<String>(
            Arrays.asList(new String[]{"Setting", "Confirm"}));


    private static Timer timer = new Timer();

    // shared by all kinds of records that can be generated by this component
    private static KeyValueList record = new KeyValueList();
    // shared by all kinds of alerts that can be generated by this component
    private static KeyValueList alert = new KeyValueList();

    private static BCIReading reading = new BCIReading();

    private static SimpleDateFormat format = new SimpleDateFormat(
            "yyyy-MM-dd HH:mm:ss");

    private static int count = 0;

    /*
     * Main program
     */
    public static void main(String[] args) {
        while (true) {
            try {

                // try to establish a connection to SISServer
                universal = connect();

                // bind the message reader to inputstream of the socket
                decoder = new MsgDecoder(universal.getInputStream());
                // bind the message writer to outputstream of the socket
                encoder = new MsgEncoder(universal.getOutputStream());

                /*
                 * construct a Connect message to establish the connection
                 */
                KeyValueList conn = new KeyValueList();
                conn.putPair("Scope", SCOPE);
                conn.putPair("MessageType", "Connect");
                conn.putPair("Role", "Basic");
                conn.putPair("Name", NAME);
                encoder.sendMsg(conn);

                initRecord();

                // KeyValueList for inward messages, see KeyValueList for
                // details
//                KeyValueList kvList;

//                while (true) {
//                    // attempt to read and decode a message, see MsgDecoder for
//                    // details
//
//
//                // dummy message
//                   kvList = decoder.getMsg();
//                    // kvList = new KeyValueList();
//                    // kvList.putPair("MessageType", "Setting");
//                    // kvList.putPair("Scope", "SIS.BCI");
//                    // kvList.putPair("Sender", "BCIGUI");
//                    // kvList.putPair("Receiver", "BCISensor");
//                    // kvList.putPair("Purpose", "Activate");
//
//                    // process that message
//                    ProcessMsg(kvList);
//                }

            } catch (Exception e) {
                // if anything goes wrong, try to re-establish the connection
                e.printStackTrace();
                try {
                    // wait for 1 second to retry
                    Thread.sleep(1000);
                } catch (InterruptedException e2) {
                }
                System.out.println("Try to reconnect");
                try {
                    universal = connect();
                } catch (IOException e1) {
                }
            }
        }
    }

    /*
     * used for connect(reconnect) to SISServer
     */
    static Socket connect() throws IOException {
        Socket socket = new Socket("127.0.0.1", port);
        return socket;
    }

    private static void initRecord() {
        record.putPair("Scope", SCOPE);
        record.putPair("MessageType", "Reading");
        record.putPair("Sender", NAME);

        // Receiver may be different for each message, so it doesn't make sense
        // to set here
        // record.putPair("Receiver", "");

        alert.putPair("Scope", SCOPE);
        alert.putPair("MessageType", "Alert");
        alert.putPair("Sender", NAME);
        alert.putPair("Purpose", "BCIAlert");

        // Receiver may be different for each message, so it doesn't make sense
        // to set here
        // alert.putPair("Receiver", "");
    }

    public static void componentTask(DataPacket_ADS1299 data, float scale_to_uV, int nchan) {
        try {
        	
        	collect(data.values, scale_to_uV, nchan);
            reading.date = System.currentTimeMillis();
            //reading
            record.putPair("uid", reading.uid + "");
            record.putPair("channels", reading.channels.length+"");
            for (int i = 0; i < reading.channels.length; i++) {
            	record.putPair("channels"+i, reading.channels[i]+"");
            }
            record.putPair("datetime", reading.date + "");
            //send reading message to GUI, uploader
            //encoder.sendMsg(record);
            //send reading message to controller
            // record.putPair("Receiver", "BCIController");
            // send to BCIMonitor
            record.putPair("Receiver", "BCIMonitor");
            record.putPair("originator","machine");
            record.putPair("Purpose","Reading");
            encoder.sendMsg(record);
            record.removePair("Receiver");
            encoder.sendMsg(record);
            
            // if (reading.temp > min && reading.temp < max) {//normal
            //     //reading
            //     reading.date = System.currentTimeMillis();
            //     record.putPair("Temp", reading.temp + "");
            //     record.putPair("Date", reading.date + "");
            //     //send reading message to GUI, uploader
            //     encoder.sendMsg(record);
            //     //send reading message to controller
            //     record.putPair("Receiver", "DiController1");
            //     encoder.sendMsg(record);
            //     record.removePair("Receiver");
            // } else { //alert
            //     alert.putPair("Temp", reading.temp + "");
            //     alert.putPair("Date", reading.date + "");
            //     //send alert message to GUI, uploader
            //     encoder.sendMsg(alert);
            //     //send alert message to controller
            //     alert.removePair("Receiver");
            //     alert.putPair("Receiver", "DiController1");
            //     encoder.sendMsg(alert);
            // }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }



	private void collect(int[] values, float scale_fac, int nchan) {
		reading.channels = new double[nchan];
        int nVal = values.length;
        for (int Ival = 0; Ival < nVal; Ival++) {
          reading.channels[Ival] = scale_fac * (float)(values[Ival]);
        }
      }

}

class BCIReading {
	 double[] channels;
	String up = "";
	String purpose = "";
	String originator = "";
	long date;
	
    String uid = "376896";
}
